### PR TITLE
Finish integrating new 5.4 ORM events

### PR DESCRIPTION
**Pull request by michaelborn**
Resolves an issue where the new events added in the Lucee Hibernate extension were not being emitted due to a missing EventListener registration.

### CODE REVIEW

**Comment by zspitzer** [comment]
@michaelborn can you add some tests for these event types? https://github.com/lucee/Lucee/pull/1369

**Comment by michaelborn** [comment]
@zspitzer Yes, I can try... can you help me get started? The Lucee test suite seems a little bizarre to me. I have a [number of event tests already written in the CBORM repo](https://github.com/michaelborn/cborm/blob/feat/Hibernate-5-flush-events/test-harness/tests/specs/EventHandlerTest.cfc#L182-L204).

**Comment by michaelborn** [comment]
I can probably PR some code to read that `application.ormEventLog` variable and look for the expected event name(s), is that correct?

**Comment by zspitzer** [comment]
1. `test/orm/events/eventHandler.cfc` needs to have names of these new event handlers
2. add examples so that when `test/orm/events/index.cfm` is run, each one is triggered
3. finally, `hibernate.testEvents()` just checks to see all the events (by count) occur

**Comment by michaelborn** [comment]
Zac, these new tests will fail if run on the 3.5 version of the Hibernate extension. Does the Lucee test suite specify any particular extension version?

**Comment by michaelborn** [comment]
I added some test code, but it's going to be tough to test this in the automated builds. I can probably test this by spinning up a custom Lucee server and pointing it at the `test/orm/events` directory... :thinking:

**Comment by michaelborn** [comment]
@zspitzer this one may have been lost in the shuffle; Can we look at merging this now that the ORM events tests are done?

**Comment by zspitzer** [comment]
@michaelborn i have moved the events tests into this repo, that way you extend the tests so this won't break the build

https://github.com/lucee/extension-hibernate/blob/5.4/tests/events.cfc

**Comment by michaelborn** [comment]
After attempting a rebase, then a force push with the new cherry-picked commit, I abandoned this PR and opened a new one:

https://github.com/lucee/extension-hibernate/pull/31

**Pull request closed without merging**
